Repository FRONTENDBOOTCAMP-13th/JS-09-Promise9, pull requests merged in 2025-05, with the labels that each got.

#6 🧪test: Add test-csj.js
  test-csj.js
Labels: ✅ test

#8 🧪test: Add test-psy.js
  .github/PULL_REQUEST_TEMPLATE.md
  test-psy.js
Labels: ✅ test

#5 🧪test: Add test-ljh.js
  test-ljh.js
Labels: ✅ test

#7 🧪test: Add test-bsb.js
  test-bsb.js
Labels: ✅ test

#10 💄style: Set up base UI styles
  index.html
  public/fonts/pretendard/pretendardvariable.css
  public/fonts/pretendard/woff2/PretendardVariable.woff2
  src/assets/img/girl-default.png
  src/assets/img/room.png
  src/counter.ts
  src/css/basic.css
  src/css/index.css
  src/css/modern-reset.css
  src/js/conversation.js
  src/main.ts
  src/pages/main.html
  test-bsb.js
  test-csj.js
  test-ljh.js
  test-psy.js
Labels: ⚙️ setting

#12 💄style: Update base UI styles
  src/pages/main.html
  src/style.css
  vite.config.js
Labels: 🎨 style

#20 🐋chore : Edit prettier.config.cjs
  prettier.config.cjs
Labels: ⚙️ setting

#21 💄style: Update styles for the result screen UI
  package-lock.json
  package.json
  prettier.config.cjs
  src/assets/img/noimg.png
  src/assets/img/playlists/happy01.jpg
  src/assets/img/playlists/playlists-happy.png
  src/assets/img/playlists/playlists-sad.png
  src/assets/img/playlists/sad01.jpg
  src/components/btn-component.html
  src/css/components.css
  src/css/result.css
  src/js/PlayMusic.ts
  src/pages/result.html
  src/style.css
  vite.config.js
Labels: ✨ feature, ⚙️ setting, 🎨 style

#23 ✨feat: Add updateMusic function
  src/assets/img/playlists/excited01.jpg
  src/assets/img/playlists/happy01.jpg
  src/assets/img/playlists/happy02.jpg
  src/assets/img/playlists/happy03.jpg
  src/assets/img/playlists/happy04.jpg
  src/assets/img/playlists/happy05.jpg
  src/js/PlayLists.ts
  src/js/PlayMusic.ts
Labels: ✨ feature

#24 ✨feat: Add emotion data saver feature
  src/js/EmotionScore.ts
Labels: ✨ feature

#26 ✨feat: Modify dialogue to objects
  src/js/branch-structure.ts
  src/pages/test.html
Labels: ✨ feature

#25 ✨ feat: Add html2canvas refactor related logic
  .gitignore
  index.html
  package-lock.json
  package.json
  public/assets/img/preview.jpg
  src/css/result.css
  src/js/KakaoApi.ts
  src/js/ResultCapture.ts
  src/main.ts
  src/pages/result.html
Labels: ✨ feature

#28 🐛bug: Resolve font loading error
  src/css/components.css
  src/pages/main.html
  src/pages/result.html
  src/pages/test.html
Labels: 🐞 bug

#31 🐛bug: Resolve img loading error
  public/assets/img/playlists/excited01.jpg
  public/assets/img/playlists/happy01.jpg
  public/assets/img/playlists/happy02.jpg
  public/assets/img/playlists/happy03.jpg
  public/assets/img/playlists/happy04.jpg
  public/assets/img/playlists/happy05.jpg
  public/assets/img/playlists/playlists-happy.png
  public/assets/img/playlists/playlists-sad.png
  public/assets/img/playlists/sad01.jpg
  src/css/result.css
  src/js/EmotionScore.ts
  src/js/PlayLists.ts
  src/js/branch-structure.ts
  src/pages/result.html
Labels: 🐞 bug

#32 🚀deploy : deploy
  public/assets/img/playlists/excited01.jpg
  public/assets/img/playlists/happy01.jpg
  public/assets/img/playlists/happy02.jpg
  public/assets/img/playlists/happy03.jpg
  public/assets/img/playlists/happy04.jpg
  public/assets/img/playlists/happy05.jpg
  public/assets/img/playlists/playlists-happy.png
  public/assets/img/playlists/playlists-sad.png
  public/assets/img/playlists/sad01.jpg
  src/css/result.css
  src/js/EmotionScore.ts
  src/js/PlayLists.ts
  src/js/branch-structure.ts
  src/pages/result.html
Labels: 🌍 deploy

#37 ✨feat: Add lonely music list to objects
  public/assets/img/playlists/excited02.jpg
  public/assets/img/playlists/excited03.jpg
  public/assets/img/playlists/excited04.jpg
  public/assets/img/playlists/excited05.jpg
  public/assets/img/playlists/fresh01.jpg
  public/assets/img/playlists/fresh02.jpg
  public/assets/img/playlists/fresh03.jpg
  public/assets/img/playlists/fresh04.jpg
  public/assets/img/playlists/fresh05.jpg
  public/assets/img/playlists/lonely01.jpg
  public/assets/img/playlists/lonely02.jpg
  public/assets/img/playlists/lonely03.jpg
  public/assets/img/playlists/lonely04.jpg
  public/assets/img/playlists/lonely05.jpg
  public/assets/img/playlists/playlists-excited.png
  public/assets/img/playlists/playlists-fresh.png
  public/assets/img/playlists/playlists-lonely.png
  public/assets/img/playlists/playlists-relax.png
  public/assets/img/playlists/relax01.jpg
  public/assets/img/playlists/relax02.jpg
  public/assets/img/playlists/relax03.jpg
  public/assets/img/playlists/relax04.jpg
  public/assets/img/playlists/relax05.jpg
  public/assets/img/playlists/sad01.jpg
  public/assets/img/playlists/sad02.jpg
  public/assets/img/playlists/sad03.jpg
  public/assets/img/playlists/sad04.jpg
  public/assets/img/playlists/sad05.jpg
  src/css/components.css
  src/css/result.css
  src/js/PlayLists.ts
  src/pages/result.html
Labels: ✨ feature

#40 ✨feat: Add emotion-data-save feature
  public/assets/img/preview.jpg
  src/js/EmotionScore.ts
  src/pages/test.html
Labels: ✨ feature

#47 💄style: Change character emotion
  src/assets/img/girl-happy.png
  src/assets/img/girl-sad.png
  src/assets/img/girl-shy.png
  src/js/branch-structure.ts
  src/pages/test.html
Labels: ✨ feature, 🎨 style

#48 ✨feat: Add easterEgg feature
  src/js/EmotionScore.ts
  src/js/branch-structure.ts
Labels: ✨ feature

#51 🍱assets: Add background image for section dialog(2)
  src/assets/img/busScene.png
  src/assets/img/cafeScene.png
  src/assets/img/clouds.png
  src/assets/img/loveScene.png
  src/assets/img/nextday.png
  src/assets/img/parkLoveScene.png
  src/assets/img/parkScene.png
  src/assets/img/sadScene.png
  src/css/result.css
  src/js/EmotionScore.ts
  src/js/PlayLists.ts
  src/js/PlayMusic.ts
  src/pages/result.html
  src/style.css
Labels: ✨ feature, 🎨 style

#57 💄style: Update styles for the btn
  public/assets/img/title-logo.png
  src/css/components.css
  src/css/main.css
  src/pages/main.html
  src/style.css
Labels: 🎨 style

#58 💬comment: Add JSDoc comments for progressBar function
  src/js/PlayMusic.ts
  src/js/result-playmusic.ts
  src/pages/result.html
Labels: 📜 docs

#63 💬comment: Update KakaoApi.ts comments in conditional logic
  src/js/KakaoApi.ts
Labels: 🛠️ refactor

#65 ✨feat: Add bgm feature
  src/js/bgm.ts
  src/pages/test.html
  src/style.css
Labels: ✨ feature

#69 ♻️refactor: Adjust play-game
  src/js/bgm.ts
  src/js/result-playmusic.ts
  src/pages/main.html
  src/pages/result.html
  src/pages/test.html
  src/style.css
Labels: 🛠️ refactor, 🎨 style

#67 ✨feat: Store high emotion value in localStorage
  src/js/branch-structure.ts
Labels: ✨ feature

#71 💄style: Add indexPages UI
  index.html
  public/assets/img/index-logo.png
  public/assets/img/project-bg.png
  src/css/index.css
  src/js/PlayLists.ts
  src/js/branch-structure.ts
  src/style.css
Labels: ✨ feature, 🛠️ refactor, 🎨 style

#74 🐛bug: Edit location link
  src/js/main.ts
  src/style.css
Labels: 🐞 bug

#75 🚀deploy : deploy
  src/js/main.ts
  src/style.css
Labels: 🌍 deploy

#77 ✨feat: Add btn capture style
  index.html
  public/assets/img/member/bsb.png
  public/assets/img/member/csj.png
  public/assets/img/member/ijh.png
  public/assets/img/member/psy.png
  public/assets/img/phone.webp
  public/favicon.svg
  public/vite.svg
  src/components/btn-component.html
  src/components/input-component.html
  src/css/components.css
  src/css/index.css
  src/css/result.css
  src/js/ResultCapture.ts
  src/pages/main.html
  src/pages/result.html
  src/pages/test.html
  src/style.css
Labels: ✨ feature, 🎨 style

#81 ✏️typo: Modify kakaoApi.ts imageURL & link Path
  public/assets/img/dokidoki.jpg
  src/js/KakaoApi.ts
Labels: 🐞 bug

#84 ✨feat: Modify emotion score check
  src/js/PlayLists.ts
Labels: 🛠️ refactor

#83 🍱assets: Modify image path
  public/assets/img/arcadeScene.png
  public/assets/img/bgmOff.png
  public/assets/img/bgmOn.png
  public/assets/img/bookstoreScene.png
  public/assets/img/boy-casual-default.png
  public/assets/img/boy-casual-happy.png
  public/assets/img/boy-casual-sad.png
  public/assets/img/boy-casual-shy.png
  public/assets/img/boy-casual-surprised.png
  public/assets/img/boy-default.png
  public/assets/img/boy-happy.png
  public/assets/img/boy-sad.png
  public/assets/img/boy-shy.png
  public/assets/img/boy-surprised.png
  public/assets/img/boy-worried.png
  public/assets/img/busScene.png
  public/assets/img/cafeScene.png
  public/assets/img/cafeteriaScene.png
  public/assets/img/classNoteScene.png
  public/assets/img/classWindowScene.png
  public/assets/img/clouds.png
  public/assets/img/clubScene.png
  public/assets/img/girl-casual-default.png
  public/assets/img/girl-casual-happy.png
  public/assets/img/girl-casual-sad.png
  public/assets/img/girl-casual-shy.png
  public/assets/img/girl-casual-surprised.png
  public/assets/img/girl-default.png
  public/assets/img/girl-happy.png
  public/assets/img/girl-sad.png
  public/assets/img/girl-shy.png
  public/assets/img/girl-surprised.png
  public/assets/img/girl-worried.png
  public/assets/img/hallwayWindowScene.png
  public/assets/img/loveScene.png
  public/assets/img/movieScene.png
  public/assets/img/nextday.png
  public/assets/img/noimg.png
  public/assets/img/parkLoveScene.png
  public/assets/img/parkScene.png
  public/assets/img/rainScene.png
  public/assets/img/rainStopScene.png
  public/assets/img/room.png
  public/assets/img/sadScene.png
  public/assets/img/scene1.png
  public/assets/img/stallScene.png
  src/js/branch-structure.ts
  src/js/conversation.js
  src/pages/test.html
  src/style.css
Labels: 🐞 bug

#91 💄style: Modify easter-egg character name
  src/css/components.css
  src/css/result.css
  src/js/branch-structure.ts
  src/pages/result.html
  src/pages/test.html
  src/style.css
Labels: 🎨 style

#90 ✨ feat: Add localStorage clear function for highScore data
  src/js/main.ts
Labels: ✨ feature

#92 🚀 deploy : deploy
  src/css/components.css
  src/css/result.css
  src/js/branch-structure.ts
  src/js/main.ts
  src/pages/result.html
  src/pages/test.html
  src/style.css
Labels: 🌍 deploy

#94 💄style: Update phone-wrap UI
  public/fonts/HS봄바람체2.0.otf
  src/css/components.css
  src/css/result.css
  src/js/ResultCapture.ts
  src/style.css
Labels: 🎨 style

#100 ♻️refactor: Improve bgm conditional structure
  src/js/bgm.ts
  src/pages/test.html
Labels: 🛠️ refactor

#107 📝docs: Update README with project info
  README.md
Labels: 📜 docs

#108 🚚rename: Rename play-lists.ts
  index.html
  src/js/result-player.ts
  src/js/result-playmusic.ts
  src/pages/result.html
  src/pages/test.html
Labels: 🐞 bug

#115 ✨feat: Add new feature to BGM module
  public/bgm/CHIME5.mp3
  public/bgm/rain.mp3
  src/js/bgm.ts
  src/pages/test.html
Labels: ✨ feature

#116 🍱assets: Add background images
  package-lock.json
  package.json
  public/assets/img/room.webp
  src/css/result.css
  src/js/result-capture.ts
  src/js/result-playmusic.ts
  src/pages/result.html
  src/pages/test.html
  src/style.css
Labels: 🐞 bug, ✨ feature, 🎨 style

#121 💄style: Update index style - 3
  index.html
  public/assets/img/index-title.png
  public/assets/img/member/bsb.png
  public/assets/img/member/bsb.webp
  public/assets/img/member/csj.png
  public/assets/img/member/csj.webp
  public/assets/img/member/ijh.png
  public/assets/img/member/ijh.webp
  public/assets/img/member/psy.png
  public/assets/img/member/psy.webp
  public/assets/img/project-bg.webp
  public/assets/img/project-intro.png
  public/assets/img/project-intro2.png
  public/assets/img/project-intro3.png
  src/css/basic.css
  src/css/index.css
  src/js/result-capture.ts
Labels: 🎨 style

#123 ✨ feat: Save random song from getRandomSong to localStorage
  index.html
  public/assets/img/caret-left.svg
  public/assets/img/caret-right.svg
  src/css/basic.css
  src/css/components.css
  src/js/branch-structure.ts
  src/js/conversation.js
  src/js/result-player.ts
  src/pages/main.html
  src/pages/test.html
  src/style.css
Labels: ✨ feature, 🎨 style

#129 🧪test: Test swiper
  index.html
  package-lock.json
  package.json
  src/css/index.css
  src/js/index.ts
  src/swiper.d.ts
  tsconfig.json
Labels: ✅ test

#136 ✨feat: Add swiper function
  index.html
  src/css/index.css
  src/js/index.ts
  src/swiper.d.ts
  src/vite-env.d.ts
Labels: ✨ feature, 🎨 style

#135 ♻️refactor: Improve conditional logic in main.ts and main.html
  src/css/components.css
  src/css/main.css
  src/js/main.ts
  src/pages/main.html
Labels: ✨ feature

#142 🐛bug: Fix swiper bug
  src/js/index.ts
  src/swiper.d.ts
Labels: 🐞 bug

#145 ✨feat: Add index.html OG(Open Graph)tag
  index.html
  src/js/branch-structure.ts
  src/js/kakao-api.ts
  src/pages/result.html
Labels: ✨ feature

#149 💄style: Improve styling index page
  index.html
  public/assets/img/Promise9-gradient.png
  public/assets/img/Promise9-gradient.webp
  public/assets/img/Promise9.png
  public/assets/img/Promise9.webp
  public/assets/img/bg-gradient.svg
  public/assets/img/controller.png
  public/assets/img/controller.webp
  src/css/components.css
  src/css/index.css
  src/css/main.css
  src/css/result.css
  src/js/branch-structure.ts
  src/js/index.ts
  src/pages/main.html
  src/pages/result.html
  src/style.css
Labels: 🎨 style

#154 💄 style: Update character image for selected input
  index.html
  public/assets/img/Promise9-gradient.png
  public/assets/img/Promise9.png
  public/assets/img/controller.png
  src/css/index.css
  src/css/main.css
  src/js/main.ts
  src/pages/main.html
Labels: ✨ feature, 🎨 style

#157 💄style: Update guide-text name
  public/assets/img/bg-sprites.webp
  public/assets/img/playlists/emotion-bg-sprites.webp
  src/css/main.css
  src/css/result.css
  src/js/branch-structure.ts
  src/js/main.ts
  src/pages/main.html
  src/style.css
  src/typescript.svg
Labels: 🐞 bug, 🎨 style

#158 ♻️ refactor: Refactor result-playmusic alert code
  src/js/bgm.ts
  src/js/result-playmusic.ts
Labels: 🐞 bug, 🛠️ refactor

#165 💄style: Update media quiery style
  src/css/index.css
  src/js/index.ts
Labels: 🐞 bug

#181 🖥️ a11y: Update meta-tag
  index.html
  src/css/index.css
  src/css/main.css
  src/pages/dokidoki-main.html
  src/pages/dokidoki-play.html
  src/pages/dokidoki-result.html
  src/style.css
Labels: 🖥️ a11y

#188 📝docs: Update READEME
  README.md
Labels: 📜 docs

#189 📝docs: Update README with project info
  README.md
Labels: 📜 docs

#191 ✏️typo: Fix comment typo
  src/css/index.css
  src/js/main.ts
Labels: 🐞 bug

#192 🚀deploy: deploy
  README.md
  src/css/index.css
  src/js/main.ts
Labels: 🌍 deploy

#193 📝docs: Update READEME
  README.md
Labels: 📜 docs

#196 🐛bug: Add forced reflow using offsetHeight after hiding prevBtn
  src/css/main.css
  src/js/branch-structure.ts
Labels: 🐞 bug

#197 🚀deploy : deploy
  README.md
  src/css/main.css
  src/js/branch-structure.ts
Labels: 🌍 deploy

#199 🐛bug: Fix music autoplay
  src/js/bgm.ts
  src/js/branch-structure.ts
  src/js/result-playmusic.ts
  src/pages/dokidoki-play.html
Labels: 🐞 bug

#201 💄style: Modify Mac user guidance
  README.md
  index.html
  public/assets/img/info-circle.svg
  src/css/main.css
  src/js/main.ts
  src/pages/dokidoki-main.html
Labels: 🖥️ a11y, 🎨 style
